services:
  postgres:
    image: postgres:latest
    container_name: codechallenge_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codechallenge_db
    ports:
      - "5432:5432"